Game: main.o minimap.o clavier.o
	gcc main.o minimap.o clavier.o -o Game -lSDL -lSDL_image -g -lSDL_ttf -lSDL_mixer 
main.o: main.c
	gcc -c main.c -g
minimap.o: minimap.c
	gcc -c minimap.c -g
clavier.o: clavier.c
	gcc -c clavier.c -g
