Game: main.o menu.o enigme.o perso.o background.o maze.o  ennemi.o minimap.o clavier.o sauvegarde.o
	gcc main.o menu.o enigme.o perso.o minimap.o clavier.o background.o maze.o sauvegarde.o ennemi.o -o Game -lSDL -lSDL_image -g -lSDL_ttf -lSDL_mixer 
main.o: main.c
	gcc -c main.c -g
menu.o: menu.c
	gcc -c menu.c -g
enigme.o: enigme.c
	gcc -c enigme.c -g
perso.o: perso.c
	gcc -c perso.c -g
background.o: background.c
	gcc -c background.c -g
maze.o: maze.c
	gcc -c maze.c -g
ennemi.o: ennemi.c
	gcc -c ennemi.c -g
minimap.o: minimap.c
	gcc -c minimap.c -g
clavier.o:clavier.c 
	gcc -c clavier.c -g
sauvegarde.o:sauvegarde.c 
	gcc -c sauvegarde.c -g
